### ISSUE TITLE
Incompatible with nodebb v1.6.x + ?

### ISSUE THREAD

**Issue by joolswills** [NodeBB/nodebb-plugin-question-and-answer#45]
When this plugin is enabled on nodebb v1.6.x I get a lot of errors logged (in frontend and in the main nodebb log). removed full install paths from snippet below.

```
TypeError: templateFunction is not a function
    at runtime (nodebb/node_modules/benchpressjs/build/lib/runtime.js:63:10)
    at Object.__express (nodebb/node_modules/benchpressjs/build/lib/express.js:22:22)
    at nodebb/src/webserver.js:133:15
    at nodebb/src/middleware/index.js:218:12
    at nextTask (nodebb/node_modules/async/dist/async.js:5297:14)
    at next (nodebb/node_modules/async/dist/async.js:5304:9)
    at nodebb/node_modules/async/dist/async.js:906:16
    at nodebb/src/file.js:142:3
    at FSReqWrap.oncomplete (fs.js:153:5)
```

I suspect the plugin needs updating ?

running on Debian Stretch x86_64 / nodebb v1.7.x / nodejs 8.9.1 / mongodb 3.4.10

**Comment by psychobunny** [comment]
It should be compatible with the latest now :)
