### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by mujibsardar** [NodeBB/nodebb-plugin-question-and-answer#60]
I was trying to build my app and I received the following build error. 

`2020-01-04T19:51:47.456Z [undefined/3808] - error: [build]           client js bundle  build failed
2020-01-04T19:51:47.457Z [undefined/3808] - error: [build] Encountered error during build step {"stack":"Error minifying node_modules/nodebb-plugin-question-and-answer/static/lib/main.js\nSyntaxError: translations redeclared\n    at JS_Parse_Error.get (eval at <anonymous> (/home/avan/nodebb/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:75:23)\n    at minifyAndSave (/home/avan/nodebb/src/meta/minifier.js:242:97)\n    at /home/avan/nodebb/src/meta/minifier.js:213:3\n    at err (/home/avan/nodebb/node_modules/async/dist/async.js:252:13)\n    at wrapper (/home/avan/nodebb/node_modules/async/dist/async.js:272:20)\n    at iterateeCallback (/home/avan/nodebb/node_modules/async/dist/async.js:425:28)\n    at /home/avan/nodebb/node_modules/async/dist/async.js:325:20\n    at _iteratee (/home/avan/nodebb/node_modules/async/dist/async.js:249:17)\n    at /home/avan/nodebb/src/meta/minifier.js:202:4\n    at /home/avan/nodebb/node_modules/graceful-fs/graceful-fs.js:115:16"}
2020-01-04T19:51:47.458Z [undefined/3808] - error: [object Object]
`

Not sure what is going on. I checked the main.js file and the translations variable seems to be used correctly. Any help would be appreciated.

**Comment by barisusakli** [comment]
@mujibsardar, this could have been caused by the `translations` variable which was a global. If any other script also declared it then you would get this error
